PeopleStock/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PeopleStock.Models;

namespace PeopleStock.Controllers
{
    public class OrganizationController : Controller
    {
        public ActionResult EditOrgAbout(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public ActionResult EditOrgAbout(int id, string About)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Id == id);
                org.about = About;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult AddOrgEvent(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddOrgEvent(int id, string Name, string Event, string Date)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Id == id);
                DateTime eventDate = DateTime.Parse(Date);
                OrganizationEvent newEvent = new OrganizationEvent()
                {
                    EventDate = eventDate,
                    EventName = Name,
                    EventText = Event,
                    OrgID = id
                };
                db.OrganizationEvents.AddObject(newEvent);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
        }

        public ActionResult About(int id)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                var org = db.Organizations.FirstOrDefault(o => o.Id == id);
                return View(org);
            }
        }

        public ActionResult Personalize(string component)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Email == User.Identity.Name);
                string fileName = Path.GetFileName(org.HeaderImgLocation);
                string modelFilePath = string.Format(Url.Content("~/Resources/{0}/{1}"), org.Name, fileName);
                PersonalizeModel model = new PersonalizeModel()
                {
                    BannerImgLocation = modelFilePath ?? "/none",
                    BannerText = org.HeaderText
                }; 
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Personalize(HttpPostedFileBase file, string BannerText)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Email == User.Identity.Name);
                string modelFilePath = "none";
                if (file != null && !string.IsNullOrEmpty(file.FileName))
                {
                    modelFilePath = UploadFile(file, org, db);
                }
                if (!string.IsNullOrEmpty(BannerText))
                {
                    org.HeaderText = BannerText;
                    db.SaveChanges();
                }
                
                PersonalizeModel model = new PersonalizeModel()
                {
                    BannerImgLocation = modelFilePath,
                    BannerText = BannerText
                }; 
                return View(model);
            }
        }

        private string UploadFile(HttpPostedFileBase file, Organization org, PeopleStockEntities db)
        {
            //does this org have its own folder?
            string dir = string.Format(Url.Content("~/Resources/{0}"), org.Name);
            string serverDir = Server.MapPath(dir);
            if (!Directory.Exists(serverDir))
            {
                Directory.CreateDirectory(serverDir);
            }

            //save the file
            string filePath = Path.Combine(serverDir, file.FileName);
            if (!System.IO.File.Exists(filePath))
            {
                file.SaveAs(filePath);
            }
            if (org.HeaderImgLocation != filePath)
            {
                org.HeaderImgLocation = filePath;
                db.SaveChanges();
            }

            string fileName = Path.GetFileName(filePath);
            string modelFilePath = string.Format("/Resources/{0}/{1}", org.Name, fileName);
            return modelFilePath;
        }

        public ActionResult AddContent()
        {
            ViewBag.OrgName = User.Identity.Name;
            return View();
        }

        [HttpPost]
        public ActionResult AddContent(HttpPostedFileBase file_data, string Title)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Email == User.Identity.Name);
                HttpPostedFileBase file_upload = file_data;
                if (Utils.IsAudioResource(file_upload.FileName))
                {
                    UploadAudioResource(file_upload, org, db, Title);
                }
                else if (Utils.IsVideoResource(file_upload.FileName))
                {
                    UploadVideoResource(file_upload, org, db, Title);
                }
                ViewBag.OrgName = User.Identity.Name;
                return View();
            }
        }

        public string Upload(string folder, HttpPostedFileBase file_upload, string orgName, string title)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization org = db.Organizations.FirstOrDefault(o => o.Email == orgName);
                string Title = title;
                foreach (string item in Request.Files)
                {
                    HttpPostedFileBase hpf = Request.Files[item] as HttpPostedFileBase;
                    if (Utils.IsAudioResource(hpf.FileName))
                    {
                        UploadAudioResource(hpf, org, db, Title);
                    }
                    else if (Utils.IsVideoResource(hpf.FileName))
                    {
                        UploadVideoResource(hpf, org, db, Title);
                    }
                }
            }
            return "Ok";
        }

        private string CreateResourceFolder(string orgName)
        {
            string dir = string.Format(Url.Content("~/Resources/{0}/Content"), orgName);
            string serverDir = Server.MapPath(dir);
            if (!Directory.Exists(serverDir))
            {
                Directory.CreateDirectory(serverDir);
            }
            return serverDir;
        }

        private void UploadAudioResource(HttpPostedFileBase file, Organization org, PeopleStockEntities db, string Title)
        {
            if (file == null) return;
            //does this org have its own folder?
            string serverDir = CreateResourceFolder(org.Name);

            //save the file
            string filePath = Path.Combine(serverDir, file.FileName);
            if (!System.IO.File.Exists(filePath))
            {
                file.SaveAs(filePath);
            }

            var existingContent = db.OrganizationContents.FirstOrDefault(o => o.Title == Title && o.OrgID == org.Id);
            if (existingContent == null)
            {
                OrganizationContent newContent = new OrganizationContent()
                {
                    ItemPath = file.FileName,
                    OrgID = org.Id,
                    Title = Title
                };
                db.OrganizationContents.AddObject(newContent);
                db.SaveChanges();
            }
        }

        private void UploadVideoResource(HttpPostedFileBase file, Organization org, PeopleStockEntities db, string Title)
        {
            //right now, we do nothing different to upload a video resource
            UploadAudioResource(file, org, db, Title);
        }

        public ActionResult RemoveContent(int orgID, int contentID)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                var contentItem = db.OrganizationContents.FirstOrDefault(o => o.Id == contentID);
                if (contentItem != null)
                {
                    db.OrganizationContents.DeleteObject(contentItem);
                    db.SaveChanges();
                }
                return RedirectToAction("MainOrg", "Home");
            }
        }
    }
}

PeopleStock/Views/Organization/About.cshtml
@{
    ViewBag.Title = "About";
}
@using PeopleStock.Models;
@model Organization

<h2>About</h2>
<br />
<label>@Model.about</label>
<br />
@Html.ActionLink("Edit", "EditOrgAbout", "Organization", new {id = Model.Id }, new { })

PeopleStock/Views/Organization/AddContent.cshtml
@{
    ViewBag.Title = "AddContent";
    string orgName = ViewBag.OrgName;
}

 <script type="text/javascript" src="@Url.Content("~/uploadify/swfobject.js")"></script>
<script type="text/javascript" src="@Url.Content("~/uploadify/jquery.uploadify.v2.1.4.min.js")"></script>
<script type="text/javascript">
// <![CDATA[
    $(document).ready(function () {
        $('#file_upload').uploadify({
            'uploader': '/peoplestock/uploadify/uploadify.swf',
            'script': '/peoplestock/Organization/Upload',
            'cancelImg': '/peoplestock/uploadify/cancel.png',
            'folder': '/peoplestock/Uploads',
            'multi': true,
            'auto': false,
            onError: function (event, queueID, fileObj, errorObj) {
                alert("Error!!! Type: [" + errorObj.type + "] Info [" + errorObj.info + "]");
            }
        });
        $("#submit").click(function () {
            var title = $("#Title").val();
            var orgName = $("#OrgName").val();
            $("#file_upload").uploadifySettings("scriptData", { "orgName": orgName, "title": title });
            $("#file_upload").uploadifyUpload();
        });
    });
// ]]>
</script>
<h2>Add Content</h2>

@{Html.BeginForm("AddContent", "Organization", FormMethod.Post, new { enctype = "multipart/form-data" });}
    @Html.Hidden("OrgName", orgName)
    <label>Upload a Resource:</label>
    <input id="file_upload" type="file" name="file_upload" />
    <label>Title:</label>
    @Html.TextBox("Title")<br />
    <input type="button" id="submit" value="Upload" />
@{Html.EndForm();}

PeopleStock/Views/Organization/AddOrgEvent.cshtml
@{
    ViewBag.Title = "AddOrgEvent";
    int id = ViewBag.Id;
}

<h2>Add Event</h2>

@{Html.BeginForm();}
    <label>Name:</label>
    <input type="text" name="Name" />
    <br />

    <label>Text:</label>
    <textarea cols="50" rows="35" name="Event"></textarea>
    <br />

    <label>Date</label>
    <input type="text" name="Date" />
    <br />

    <input type="hidden" name="id" value="@id" />
    <input type="submit" name="submit" value="submit" />
@{Html.EndForm();}

PeopleStock/Views/Organization/EditOrgAbout.cshtml
@{
    ViewBag.Title = "EditOrgAbout";
    int id = ViewBag.Id;
}

<h2>Edit About</h2>
@{Html.BeginForm();}
    <textarea cols="50" rows="35" name="About">

    </textarea>
    <br />
    <input type="hidden" name="id" value="@id" />
    <input type="submit" name="submit" value="submit" />
@{Html.EndForm();}

PeopleStock/Views/Organization/Personalize.cshtml
@model PeopleStock.Models.PersonalizeModel
@{
    ViewBag.Title = "Personalize";
}

<h2>Personalize</h2>

@{Html.BeginForm("Personalize","Organization",FormMethod.Post,new { enctype = "multipart/form-data" });}
    <label>Select Banner:</label><br />
    <input type="file" name="file" /><br />
    <label>Preview</label>
    <div>
        <img src="@Model.BannerImgLocation" alt="none" class="bannerThumb" width="300" height="300" />
    </div>
    <br />
    @Html.LabelFor(model => model.BannerText)
    @Html.EditorFor(model => model.BannerText)
    <br />
    <input type="submit" value="Save" />
@{Html.EndForm();}