PeopleStock/Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PeopleStock.Models;

namespace PeopleStock.Controllers
{
    public class ContentController : Controller
    {
        //
        // GET: /Content/

        public ActionResult AddContent(int id)
        {
            ViewBag.PersonID = id;
            return View();
        }

        [HttpPost]
        public ActionResult AddContent(int PersonID, string Content)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                DateTime currTime = DateTime.Now;
                personStatu newContent = new personStatu()
                {
                    Content = Content,
                    DateCreated = currTime,
                    PersonID = PersonID
                };
                db.personStatus.AddObject(newContent);
                db.SaveChanges();
                return RedirectToAction("Main", "Home");
            }
        }

        public ActionResult AddOrgContent(int id)
        {
            OrganizationStatu newStatus = new OrganizationStatu();
            newStatus.OrgID = id;
            return View(newStatus);
        }

        [HttpPost]
        public ActionResult AddOrgContent(int id, OrganizationStatu newStatus)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                newStatus.DateCreated = DateTime.Now;
                newStatus.OrgID = id;
                newStatus.Id = -1;
                db.OrganizationStatus.AddObject(newStatus);
                db.SaveChanges();
                return RedirectToAction("MainOrg", "Home");
            }
        }
    }
}

PeopleStock/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

using PeopleStock.Models;

namespace PeopleStock.Controllers
{
    public class RegisterController : Controller
    {
        public ActionResult RegisterPerson()
        {
            return View();
        }

        public ActionResult RegisterOrg()
        {
            Organization org = new Organization();
            return View(org);
        }

        [HttpPost]
        public ActionResult RegisterOrg(string Name, string Email, string Passphrase)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                Organization newOrg = new Organization()
                {
                    Email = Email,
                    Name = Name,
                    Passphrase = Passphrase,
                    StockValue = Constants.StartingOrgStockValue
                };
                var currOrg = db.Organizations.FirstOrDefault(o => o.Name == Name);
                if (currOrg != null)
                {
                    string errorMessage = "Organization already exists.";
                    return RedirectToAction("Error", "Error", new {ErrorMessage = errorMessage });
                }
                db.Organizations.AddObject(newOrg);
                db.SaveChanges();

                //create a default user to represent this org
                Person orgPerson = new Person()
                {
                    Email = newOrg.Email,
                    FullName = newOrg.Name,
                    Passphrase = newOrg.Passphrase
                };
                db.People.AddObject(orgPerson);
                db.SaveChanges();

                int sellStatus = Status.GetStatus(Constants.StockStatus.Sell);

                //create stocks for the new org
                OrganizationStock newStock = new OrganizationStock()
                {
                    NumStocks = Constants.StartingOrgStockCount,
                    OrgStockID = newOrg.Id,
                    OwnerID = orgPerson.Id,
                    SellValue = 1,
                    StatusID = sellStatus,
                };
                db.OrganizationStocks.AddObject(newStock);
                db.SaveChanges();

                FormsAuthentication.SetAuthCookie(newOrg.Email, false);
                return RedirectToAction("MainOrg", "Home");
            }
        }

    }
}

PeopleStock/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PeopleStock.Models;

namespace PeopleStock.Controllers
{
    public class TransactionController : Controller
    {
        //
        // GET: /Transaction/

        public ActionResult SearchStock()
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                var stocks = db.PersonStocks.Include("Person").Where(o => o.Status.Name == Constants.StockStatus.Sell)
                    .OrderBy(o => o.Person1.FullName).ToList();
                var orgStocks = db.OrganizationStocks.Include("Person").Include("Organization").Where(o => o.Status.Name == Constants.StockStatus.Sell)
                    .OrderBy(o => o.Organization.Name).ToList();
                SearchStockModel model = new SearchStockModel();
                model.PersonStocks = stocks;
                model.OrgStocks = orgStocks;
                return View(model);
            }
        }

        public ActionResult BuyStock(int id)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                var stock = db.PersonStocks.Include("Person").FirstOrDefault(o => o.Id == id);
                var currUser = db.People.FirstOrDefault(o => o.Email == User.Identity.Name);
                var tradeStocks = db.PersonStocks.Where(o => o.OwnerID == currUser.Id);
                var orgTradeStocks = db.OrganizationStocks.Where(o => o.OwnerID == currUser.Id);
                string stockName = stock.Person1.FullName;
                BuyStockModel model = new BuyStockModel()
                {
                    PurchaseStock = stock,
                    TradeStocks = tradeStocks.ToList(),
                    OrgTradeStocks = orgTradeStocks.ToList()
                };
                foreach (var tradeStock in tradeStocks)
                {
                    string name = tradeStock.NumStocks.ToString();
                    name = tradeStock.Person1.FullName;
                }
                foreach (var orgStock in orgTradeStocks)
                {
                    string orgName = orgStock.Organization.Name;
                }

                return View(model);
            }
        }

        [HttpPost]
        public ActionResult BuyStock(int PurchaseStockID, int PurchaseAmount, int[] stockQty, int[] stockID,int[] stockOrgQty, int[] stockOrgID)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                PersonStock stock = db.PersonStocks.FirstOrDefault(o => o.Id == PurchaseStockID);
                Person currUser = db.People.FirstOrDefault(o => o.Email == User.Identity.Name);
                Person ownerUser = db.People.FirstOrDefault(o => o.Id == stock.Person.Id);
                
                //trade person stocks from the initiator to the owner
                TradePersonStocks(stockID, stockQty, ownerUser, db);
                TradeOrgStocks(stockOrgQty, stockOrgID, ownerUser, db);

                //trade stock that the initiator purchased
                TradePersonStock(PurchaseStockID, PurchaseAmount, currUser, db);

                //log the transaction
                string logMessage = GetLogMessage(PurchaseStockID,PurchaseAmount,stockQty, stockID, stockOrgQty, stockOrgID, db);
                PersonStockTransaction trans = new PersonStockTransaction()
                {
                    PersonID = ownerUser.Id,
                    TransactionText = logMessage,
                    DateCreated = DateTime.Now
                };
                db.PersonStockTransactions.AddObject(trans);
                db.SaveChanges();

                return RedirectToAction("Main", "Home");
            }
        }

        private string GetLogMessage(int stockID, int qty, int[] stockQty, int[] stockIDs, int[] stockOrgQty, int[] stockOrgID, PeopleStockEntities db)
        {
            string msg = string.Empty;
            string subMsg = string.Empty;
            string msgTemplate = "{0} traded you {1} for {2} of {3}";
            string msgSubTemplate = "{0} of {1};";
            Person currUser = db.People.FirstOrDefault(o => o.Email == User.Identity.Name);

            PersonStock stock = db.PersonStocks.FirstOrDefault(o => o.Id == stockID);
            subMsg = GetLogMessage_Person(msgSubTemplate, stockQty, stockIDs, db);
            subMsg += GetLogMessage_Org(msgSubTemplate, stockOrgQty, stockOrgID, db);

            msg = string.Format(msgTemplate, currUser.FullName, subMsg, qty.ToString(), stock.Person1.FullName);

            return msg;
        }
        private string GetOrgLogMessage(int stockID, int qty, int[] stockQty, int[] stockIDs, int[] stockOrgQty, int[] stockOrgID, PeopleStockEntities db)
        {
            string msg = string.Empty;
            string subMsg = string.Empty;
            string msgTemplate = "{0} traded you {1} for {2} of {3}";
            string msgSubTemplate = "{0} of {1}";
            Person currUser = db.People.FirstOrDefault(o => o.Email == User.Identity.Name);

            OrganizationStock stock = db.OrganizationStocks.FirstOrDefault(o => o.Id == stockID);
            for (int i = 0; i < stockQty.Length; i++)
            {
                int currQty = stockQty[i];
                int currID = stockIDs[i];
                if (currQty <= 0) continue;
                PersonStock currStock = db.PersonStocks.FirstOrDefault(o => o.Id == currID);
                if (currStock == null) continue;
                subMsg += string.Format(msgSubTemplate, currQty.ToString(), currStock.Person1.FullName);
            }
            for (int i = 0; i < stockOrgQty.Length; i++)
            {
                int currQty = stockOrgQty[i];
                int currID = stockOrgID[i];
                if (currQty <= 0) continue;
                OrganizationStock currStock = db.OrganizationStocks.FirstOrDefault(o => o.Id == currID);
                if (currStock == null) continue;
                subMsg += string.Format(msgSubTemplate, currQty.ToString(), currStock.Organization.Name);
            }

            msg = string.Format(msgTemplate, currUser.FullName, subMsg, qty.ToString(), stock.Organization.Name);

            return msg;
        }
        private string GetLogMessage_Person(string msgSubTemplate, int[] stockQty, int[] stockIDs, PeopleStockEntities db)
        {
            if (stockQty == null) return string.Empty;
            string msg = string.Empty;
            for (int i = 0; i < stockQty.Length; i++)
            {
                int currQty = stockQty[i];
                int currID = stockIDs[i];
                if (currQty <= 0) continue;
                PersonStock currStock = db.PersonStocks.FirstOrDefault(o => o.Id == currID);
                if (currStock == null) continue;
                msg += string.Format(msgSubTemplate, currQty.ToString(), currStock.Person1.FullName);
            }
            return msg;
        }
        private string GetLogMessage_Org(string msgSubTemplate,int[] stockOrgQty, int[] stockOrgID, PeopleStockEntities db)
        {
            if (stockOrgQty == null) return string.Empty;
            string msg = string.Empty;
            for (int i = 0; i < stockOrgQty.Length; i++)
            {
                int currQty = stockOrgQty[i];
                int currID = stockOrgID[i];
                if (currQty <= 0) continue;
                OrganizationStock currStock = db.OrganizationStocks.FirstOrDefault(o => o.Id == currID);
                if (currStock == null) continue;
                msg += string.Format(msgSubTemplate, currQty.ToString(), currStock.Organization.Name);
            }
            return msg;
        }

        public ActionResult StockSettings(int id)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                PersonStock stock = db.PersonStocks.FirstOrDefault(o => o.Id == id);
                return View(stock);
            }
        }

        [HttpPost]
        public ActionResult StockSettings(int id, string rdoSell, string SellValue)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                PersonStock stock = db.PersonStocks.FirstOrDefault(o => o.Id == id);
                if (rdoSell == "Sell")
                {
                    decimal dSellValue = decimal.Parse(SellValue);
                    Status sellStatus = db.Status.FirstOrDefault(o => o.Name == Constants.StockStatus.Sell);
                    stock.StatusID = sellStatus.Id;
                    stock.SellValue = dSellValue;
                }
                else
                {
                    Status holdStatus = db.Status.FirstOrDefault(o => o.Name == Constants.StockStatus.Hold);
                    stock.StatusID = holdStatus.Id;
                }
                db.SaveChanges();
                return RedirectToAction("Main", "Home");
            }
        }

        public ActionResult OrgStockSettings(int id)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                OrganizationStock stock = db.OrganizationStocks.FirstOrDefault(o => o.Id == id);
                return View(stock);
            }
        }

        [HttpPost]
        public ActionResult OrgStockSettings(int id, string rdoSell, string SellValue)
        {
            using (PeopleStockEntities db = new PeopleStockEntities())
            {
                OrganizationStock stock = db.OrganizationStocks.FirstOrDefault(o => o.Id == id);
                if (rdoSell == "Sell")
                {
                    decimal dSellValue = decimal.Parse(SellValue);
                    Status sellStatus = db.Status.FirstOrDefault(o => o.Name == Constants.StockStatus.Sell);
                    stock.StatusID = sellStatus.Id;
                    stock.SellValue = dSellValue;
                }

PeopleStock/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<pre>
     Welcome to peoplestock.com. 

     What is this site all about? It's about owning a virtual piece of your favorite things. For example, let's pretend that you like the band
     'Nirvana'. You can search and find the band, and buy some of their stock, thus owning a virtual stake in the band.

     What does this mean? Do you really own part of the band? Well, no..of course not. You own a virtual share of the band. However, the intent of
     this site is to provide a new means for artists to connect with their fans. Our hope is that owning stock in the band will make special
     perks and benefits accessible to you, and that is what we're here for. Our representatives are hard at work, even this very minute, contacting
     anyone and everyone, trying to get special deals of intereset to make your stock shares THAT much more beneficial.

     Besides, who wouldn't like to be able to say that they own 50% of Bill Gates or President Obama?

     Happy Trading!
</pre>

PeopleStock/Views/Home/Feedback.cshtml
@{
    ViewBag.Title = "Feedback";
}
@model List<PeopleStock.Models.Feedback>

<h2>Feedback</h2>
@{
    <table border="1">
        <thead>
            <tr>
                <th>Title</th>
                <th>Message</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach(var feedbackItem in Model){
            <tr>
                <td>@feedbackItem.Title</td>
                <td>@feedbackItem.Feedback1</td>
                <td>@Html.ActionLink("Remove","RemoveFeedback","Home",new {id = feedbackItem.Id},null)</td>
            </tr>
    }
        </tbody>
    </table>
}


@{Html.BeginForm();}
    <label>Title:</label>
    @Html.TextBox("Title")
    <br />

    <label>Message</label>
    @Html.TextArea("Message")
    <br />
    <input type="submit" value="submit" />
@{Html.EndForm();}

PeopleStock/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@{
    
}

<div id="divLanding">
    <div>
        @Html.ActionLink("Register as a Person","Register", "Account")<br />
    </div>
    <div>
        @Html.ActionLink("Register as an Org.","RegisterOrg", "Register")
    </div>
    <div class="full">
        <div id="back_image"></div>
        <div id="hover_image"></div>
    </div>
</div>

PeopleStock/Views/Home/Main.cshtml
@model PeopleStock.Models.MainpageModel
@using PeopleStock.Models;
@using PeopleStock;
@{
    ViewBag.Title = "Main";
}

<div id="divMainArea">
    <div id="divAvatar">
        <img src="@Url.Content("~/Images/mikey.jpg")" alt="profilePic" />
        <label>@Model.CurrentPerson.FullName</label><br />

    </div>
    <div id="divStatus">
    </div>
    <div id="divMain">
        <div class="header">
            <label>Main Content</label>
            @Html.ActionLink("Add Content", "AddContent", "Content", new { id = Model.CurrentPerson.Id }, new { })
        </div>
        @{
            foreach (personStatu content in Model.Content)
            {
                <label class="subheader">@content.DateCreated</label><br />
                <label class="postContent">@content.Content</label>
                <br />
            }
        }
        <div class="spacer"></div>
        <div id="divStocks">
            <label>Your Stocks:</label>
            <table>
                <thead>
                    <tr>
                        <th>Person</th>
                        <th>Stocks</th>
                        <th>Valuation</th>
                        <th>Total Value</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

            @{
                foreach (var stock in Model.CurrentPerson.PersonStocks)
                {
                    decimal totalValue = stock.NumStocks.Value * stock.Person1.StockValue.Value;
                    string stockSetting = string.Empty;
                    string settingsLink = Html.ActionLink("Settings", "StockSettings", "Transaction", new { id = stock.Id }, new { }).ToHtmlString();
                    if (stock.isViewed == null || !stock.isViewed.Value)
                    {
                        stockSetting = settingsLink = "not viewed yet";
                    }
                    else if (stock.Status.Name == Constants.StockStatus.Hold)
                    {
                        stockSetting = "hold";
                    }
                    else
                    {
                        stockSetting = string.Format("Sell: {0}c", stock.SellValue);
                    }
                    <tr>
                        <td>@Html.ActionLink(stock.Person1.FullName, "ViewPersonalPage", "Home", new { loggedInUserId = Model.CurrentPerson.Id, viewUserId = stock.Person1.Id }, new { })</td>
                        <td>@stock.NumStocks</td>
                        <td>@String.Format("{0:0.00}", stock.Person1.StockValue)</td>
                        <td>@String.Format("{0:0.00}", totalValue)</td>
                        <td>@stockSetting</td>
                        <td>@Html.Raw(settingsLink)</td>
                    </tr>  
                }
                foreach (var stock in Model.CurrentPerson.OrganizationStocks)
                {
                    decimal totalValue = stock.NumStocks.Value * stock.Organization.StockValue.Value;
                    string stockSetting = string.Empty;
                    string settingsLink = Html.ActionLink("Settings", "OrgStockSettings", "Transaction", new { id = stock.Id }, new { }).ToHtmlString();
                    if(stock.isViewed == null || !stock.isViewed.Value){
                        stockSetting = settingsLink = "not viewed yet";   
                    }
                    else if (stock.Status.Name == Constants.StockStatus.Hold)
                    {
                        stockSetting = "hold";
                    }
                    else
                    {
                        stockSetting = string.Format("Sell: {0}c", stock.SellValue);
                    }
                    <tr>
                        <td>@Html.ActionLink(stock.Organization.Name, "ViewOrgPage", "Home", new { loggedInUserId = Model.CurrentPerson.Id, viewOrgId = stock.Organization.Id }, new { })</td>
                        <td>@stock.NumStocks</td>
                        <td>@stock.Organization.StockValue</td>
                        <td>@totalValue</td>
                        <td>@stockSetting</td>
                        <td>@Html.Raw(settingsLink)</td>
                    </tr>  
                }
            }
                </tbody>
            </table>
            <br />
            @Html.ActionLink("Buy Stock", "SearchStock", "Transaction", new { }, new { })
        </div>
        <div class="spacer"></div>
        <div id="divStockActivity">
            <label>Recent Stock Activity:</label>
            <ul>
                @{
                    foreach(var transacton in Model.Transactions){
                        <li>@transacton.TransactionText</li>   
                    }
                }
            </ul>
        </div>
    </div>
</div>

PeopleStock/Views/Home/MainOrg.cshtml
@{
    ViewBag.Title = "MainOrg";
}
@using PeopleStock.Models;
@model MainOrgPageModel
<script src="@Url.Content("~/Players/flowplayer/example/flowplayer-3.2.6.min.js")" type="text/javascript"></script>

@helper addAudioItem(string title, string picPath, string itemPath, int id)
    {
    <div class="divFeaturedItem">
        <div class="divFeaturedItemImg">
            <img src="@Url.Content("~/Images/music-icon.jpg")" alt="" />
        </div>
        <div class="divFeaturedItemDesc">
            <label>@title</label><br />
        </div>
        <div class="divFeaturedItemContent">
            <embed type="application/x-shockwave-flash" flashvars="audioUrl=@itemPath" 
        src="http://www.google.com/reader/ui/3523697345-audio-player.swf" 
        width="400" height="27" quality="best"></embed>
        </div>
        <div class="divFeaturedItemOptions">
            @Html.ActionLink("Remove","RemoveContent","Organization", new {orgID = Model.Org.Id, contentID = id}, null)
        </div>
        <br /><br />
    </div>
}
@helper addVideoItem(string title, string itemPath, int id)
    {
        string playerID = "player" + id;
        string playerPath = Url.Content("~/Players/flowplayer/flowplayer-3.2.7.swf");
    <div class="VideoItemContainer">
        <label>@title</label><br />
        <div class="divVideoItem">
            <a  href="@itemPath" 
	            style="display:block;width:425px;height:300px;" 
	            id="@playerID">
            </a>
            <script language="JavaScript" type="text/javascript">
                flowplayer(@playerID, "@playerPath", {
                    clip: { autoPlay: false }
                });
             </script>
        </div>
        <div class="divVideoOptions">
            @Html.ActionLink("Remove", "RemoveContent", "Organization", new { orgID = Model.Org.Id, contentID = id }, null)
        </div>
    </div>
        <br />
}
<div id="divMainArea">
    <div id="divAvatar">
        <img src="" alt="" />
        <label>@Model.Org.Name</label>

        <div id="divAbout">
            @Html.ActionLink("About", "About", "Organization", new { id = @Model.Org.Id }, new { })
        </div>
        <div id="divStock">
            @Html.ActionLink("Buy / Trade Stock", "BuyStock")
        </div>
        <div id="divEvents">
            <h4>Events</h4>
            <ul>
            @{
                foreach (var orgEvent in Model.OrgEvents)
                {
                 <li>
                    <label>@orgEvent.EventDate </label>
                    <label> @orgEvent.EventName</label><br />
                    <label>@orgEvent.EventText</label>
                 </li>   
                }
            }
            </ul>
            <br />
            @Html.ActionLink("Add Event", "AddOrgEvent", "Organization", new { id = Model.Org.Id }, new { })
        </div>
    </div>
    <div id="divMain">
        <div id="divHeader">
            <a href="@Url.Content("~/Organization/Personalize?component=Banner")" title="click to change">
                <img src="@Model.BannerImgPath" alt="" />
            </a>
            <a href="@Url.Content("~/Organization/Personalize?component=Header")" title="click to change" class="bannerText">
                <label>@Model.Org.HeaderText</label>
            </a>
        </div>
         <div class="header">
            <label>Main Content</label>
            @Html.ActionLink("Add Content", "AddOrgContent", "Content", new { id = Model.Org.Id }, new { })
        </div>
        @{
            foreach (OrganizationStatu content in Model.OrgStatus)
            {
                <label class="subheader">@content.DateCreated</label><br />
                <label class="postContent">@content.Content</label>
                <br />
            }
        }
        <div class="spacer"></div>
        <div id="divSpecial">
            <h4>--Stock Holder Specials--</h4>
        </div>
        <div class="spacer"></div>
        <div id="divFeaturedContent">
            <h4>Content</h4>
            <div id="VideoOptions">
                @Html.ActionLink("Add", "AddContent", "Organization")
            </div>
            <hr />
            <h4>Audio Content</h4>
            @{
                foreach (var content in Model.AudioContent)
                {
                    string path = string.Format(Url.Content("~/Resources/{0}/Content/{1}"), Model.Org.Name, content.ItemPath);
                    @addAudioItem(content.Title, string.Empty, path, content.Id)
                }
                <br /><br /><hr />
                <h4>Video Content</h4><br />
                foreach (var content in Model.VideoContent)
                {
                    string path = string.Format(Url.Content("~/Resources/{0}/Content/{1}"), Model.Org.Name, content.ItemPath);
                    @addVideoItem(content.Title, path, content.Id)
                }
            }
            
        </div>

    </div>
</div>

PeopleStock/Views/Home/ViewOrgPage.cshtml
@using PeopleStock.Models;
@model MainOrgPageModel



<script src="@Url.Content("~/Players/flowplayer/example/flowplayer-3.2.6.min.js")" type="text/javascript"></script>

@helper addAudioItem(string title, string picPath, string itemPath, int id)
    {
    <div class="divFeaturedItem">
        <div class="divFeaturedItemImg">
            <img src="@Url.Content("~/Images/music-icon.jpg")" alt="" />
        </div>
        <div class="divFeaturedItemDesc">
            <label>@title</label><br />
        </div>
        <div class="divFeaturedItemContent">
            <embed type="application/x-shockwave-flash" flashvars="audioUrl=@itemPath" 
        src="http://www.google.com/reader/ui/3523697345-audio-player.swf" 
        width="400" height="27" quality="best"></embed>
        </div>
        <div class="divFeaturedItemOptions">
            @Html.ActionLink("Remove","RemoveContent","Organization", new {orgID = Model.Org.Id, contentID = id}, null)
        </div>
        <br /><br />
    </div>
}
@helper addVideoItem(string title, string itemPath, int id)
    {
        string playerID = "player" + id;
        string playerPath = Url.Content("~/Players/flowplayer/flowplayer-3.2.7.swf");
    <div class="VideoItemContainer">
        <label>@title</label><br />
        <div class="divVideoItem">
            <a  href="@itemPath" 
	            style="display:block;width:425px;height:300px;" 
	            id="@playerID">
            </a>
            <script language="JavaScript" type="text/javascript">
                flowplayer(@playerID, "@playerPath", {
                    clip: { autoPlay: false }
                });
             </script>
        </div>
        <div class="divVideoOptions">
            @Html.ActionLink("Remove", "RemoveContent", "Organization", new { orgID = Model.Org.Id, contentID = id }, null)
        </div>
    </div>
        <br />
}
<div id="divMainArea">
    <div id="divAvatar">
        <img src="" alt="" />
        <label>@Model.Org.Name</label>
        <div id="divAbout">
            @Html.ActionLink("About", "About", "Organization", new { id = @Model.Org.Id }, new { })
        </div>
        <div id="divStock">
            @Html.ActionLink("Buy / Trade Stock", "BuyStock")
        </div>
        <div id="divEvents">
            <h4>Events</h4>
            <ul>
            @{
                foreach (var orgEvent in Model.OrgEvents)
                {
                 <li>
                    <label>@orgEvent.EventDate </label>
                    <label> @orgEvent.EventName</label><br />
                    <label>@orgEvent.EventText</label>
                 </li>   
                }
            }
            </ul>
            <br />
        </div>
        <br /><br />
    </div>
    <div id="divMain">
        <div id="divHeader">
            <img src="@Model.BannerImgPath" alt="" />
            <label>@Model.Org.HeaderText</label>
        </div>
        @{
            foreach (OrganizationStatu content in Model.OrgStatus)
            {
                <label class="subheader">@content.DateCreated</label><br />
                <label class="postContent">@content.Content</label>
                <br />
            }
        }
        <div class="spacer"></div>
        <div id="divSpecial">
            <h4>--Stock Holder Specials--</h4>
        </div>
        <div class="spacer"></div>
        <div id="divFeaturedContent">
            <h4>Content</h4>
            <div id="VideoOptions"></div>
            <hr />
            <h4>Audio Content</h4>
            @{
                foreach (var content in Model.AudioContent)
                {
                    string path = string.Format(Url.Content("~/Resources/{0}/Content/{1}"), Model.Org.Name, content.ItemPath);
                    @addAudioItem(content.Title, string.Empty, path, content.Id)
                }
                <br /><br /><hr />
                <h4>Video Content</h4><br />
                foreach (var content in Model.VideoContent)
                {
                    string path = string.Format(Url.Content("~/Resources/{0}/Content/{1}"), Model.Org.Name, content.ItemPath);
                    @addVideoItem(content.Title, path, content.Id)
                }
            }
            @{Html.BeginForm(new { C = 1, D = 2 });}
        </div>
    </div>
</div>